# 로깅
logging:
  level:
    root: info
    org.springframework.boot.web: info

spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:~/test
  h2:
    console:
      enabled: true

server:
  port: 8000

# API 관련
api:
  ## 가중치
  weight:
    theme: 10
    explain: 8
    detailExplain: 5
